# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbxZEC5MAg9VUGtwWEz7jIB6nD2w2S4W
"""

import pandas as pd
data = {
    'Ism': ['Ali', 'Vali', 'Anvar', 'Xurshid', 'Sardor'],
    'Yosh': [22, 23, 24, 25, 26],
    'Shahar': ['Toshkent', 'Samarkand', 'Buxoro', 'Toshkent', 'Fergana']
}
df = pd.DataFrame(data)
age_filter = df['Yosh'] < 24
city_filter = df['Shahar'] == 'Toshkent'
combined_filter = age_filter & city_filter
filtered_df = df[combined_filter]
print(filtered_df)